-- =========================================================================
-- SUPABASE SCHEMA EXTENSION: WEB PORTAL, AUTH & MONETIZATION
-- Tables: WebUsers, TournamentSponsors, AffiliateProducts, SponsorClickLogs
-- =========================================================================

BEGIN;

-- 1. Web Master Admin Users (For Password-Based Super Admin & Developer Access)
CREATE TABLE IF NOT EXISTS "WebUsers" (
    "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "username" TEXT UNIQUE NOT NULL,
    "password_hash" TEXT NOT NULL,
    "role" TEXT DEFAULT 'super_admin', -- 'super_admin' or 'admin'
    "discord_id" TEXT, -- Optional linked Discord ID
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    "last_login" TIMESTAMP WITH TIME ZONE
);

-- 2. Tournament Sponsorship Banners
CREATE TABLE IF NOT EXISTS "TournamentSponsors" (
    "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "guild_id" TEXT NOT NULL,
    "tournament_id" TEXT, -- NULL means server-wide sponsor
    "sponsor_name" TEXT NOT NULL,
    "banner_image_url" TEXT NOT NULL,
    "target_url" TEXT NOT NULL,
    "slot_position" TEXT DEFAULT 'top_banner', -- 'top_banner', 'sidebar', 'bracket_footer', 'stage_sponsor'
    "impressions_count" BIGINT DEFAULT 0,
    "clicks_count" BIGINT DEFAULT 0,
    "is_active" BOOLEAN DEFAULT true,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Affiliate Gaming Store Products & Widgets
CREATE TABLE IF NOT EXISTS "AffiliateProducts" (
    "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "game_category" TEXT NOT NULL, -- e.g. 'Valorant', 'BGMI', 'Free Fire', 'General'
    "product_name" TEXT NOT NULL,
    "product_category" TEXT NOT NULL, -- 'mouse', 'headset', 'currency', 'controller', 'keyboard'
    "image_url" TEXT NOT NULL,
    "affiliate_url" TEXT NOT NULL,
    "badge_text" TEXT, -- e.g. 'Top Pick', '10% Off Diamonds', 'Pro Setup'
    "price_display" TEXT,
    "display_order" INT DEFAULT 0,
    "is_active" BOOLEAN DEFAULT true,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. Sponsor Click Analytics Log
CREATE TABLE IF NOT EXISTS "SponsorClickLogs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "sponsor_id" UUID REFERENCES "TournamentSponsors"("id") ON DELETE CASCADE,
    "guild_id" TEXT,
    "tournament_id" TEXT,
    "user_ip_hash" TEXT,
    "user_agent" TEXT,
    "timestamp" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. Audit & Activity Logs (Organizer & Admin Activities)
CREATE TABLE IF NOT EXISTS "ActivityLogs" (
    "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "timestamp" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    "action_type" TEXT NOT NULL,
    "actor" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "target" TEXT,
    "category" TEXT DEFAULT 'organizer', -- 'organizer' or 'admin'
    "guild_id" TEXT,
    "metadata" JSONB DEFAULT '{}'::jsonb
);

-- 6. Discord Bot Slash Commands & Customization Configuration
CREATE TABLE IF NOT EXISTS "CommandConfigs" (
    "guild_id" TEXT PRIMARY KEY,
    "commands" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Create Indexes for fast querying
CREATE INDEX IF NOT EXISTS idx_sponsors_guild ON "TournamentSponsors"("guild_id");
CREATE INDEX IF NOT EXISTS idx_sponsors_active ON "TournamentSponsors"("is_active");
CREATE INDEX IF NOT EXISTS idx_affiliates_game ON "AffiliateProducts"("game_category");
CREATE INDEX IF NOT EXISTS idx_affiliates_active ON "AffiliateProducts"("is_active");
CREATE INDEX IF NOT EXISTS idx_activity_logs_cat ON "ActivityLogs"("category");
CREATE INDEX IF NOT EXISTS idx_activity_logs_time ON "ActivityLogs"("timestamp" DESC);

-- Grant permissions to anon and authenticated roles
ALTER TABLE "WebUsers" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "TournamentSponsors" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "AffiliateProducts" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "SponsorClickLogs" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ActivityLogs" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "CommandConfigs" DISABLE ROW LEVEL SECURITY;

GRANT ALL ON "WebUsers" TO anon, authenticated, service_role;
GRANT ALL ON "TournamentSponsors" TO anon, authenticated, service_role;
GRANT ALL ON "AffiliateProducts" TO anon, authenticated, service_role;
GRANT ALL ON "SponsorClickLogs" TO anon, authenticated, service_role;
GRANT ALL ON "ActivityLogs" TO anon, authenticated, service_role;
GRANT ALL ON "CommandConfigs" TO anon, authenticated, service_role;

-- Seed default master admins into WebUsers
INSERT INTO "WebUsers" ("username", "password_hash", "role", "discord_id")
VALUES 
    ('admin', 'a50e562ec42877cb5b9d135ea3975b55$418edbebdc72b65c0b115810166852388620a1da1665f9eb14223646fdec6c79', 'super_admin', '1303887060754497569'),
    ('Hokageadmin', '9b10507984f7aa0936d845b3ec5d7a7e$d83f356378a6a4cb8b10300b18cd782d28caf2eb402b9880f2df86dda59e5a01', 'admin', NULL)
ON CONFLICT ("username") DO NOTHING;

COMMIT;
