-- =========================================================================
-- DATABASE MIGRATION SCRIPT FOR TOURNAMENT BOT (SAFE & RE-RUN FRIENDLY)
-- Run this in your Supabase SQL Editor AFTER the tournament ends.
-- =========================================================================

BEGIN;

-- 1. Safely rename existing tables to safeguard data (Only rename if _old does NOT exist yet)
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'GuildConfig_old') AND EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'GuildConfig') THEN
        ALTER TABLE "GuildConfig" RENAME TO "GuildConfig_old";
    END IF;

    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'Tournaments_old') AND EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'Tournaments') THEN
        ALTER TABLE "Tournaments" RENAME TO "Tournaments_old";
    END IF;

    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'Events_old') AND EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'Events') THEN
        ALTER TABLE "Events" RENAME TO "Events_old";
    END IF;

    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'Results_old') AND EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'Results') THEN
        ALTER TABLE "Results" RENAME TO "Results_old";
    END IF;

    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'Deadlines_old') AND EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'Deadlines') THEN
        ALTER TABLE "Deadlines" RENAME TO "Deadlines_old";
    END IF;

    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'JudgeAssignments_old') AND EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'JudgeAssignments') THEN
        ALTER TABLE "JudgeAssignments" RENAME TO "JudgeAssignments_old";
    END IF;

    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'StaffStats_old') AND EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'StaffStats') THEN
        ALTER TABLE "StaffStats" RENAME TO "StaffStats_old";
    END IF;
END $$;

-- 2. Drop existing new tables if present from a previous failed run attempt
DROP TABLE IF EXISTS "MatchStaff" CASCADE;
DROP TABLE IF EXISTS "Matches" CASCADE;
DROP TABLE IF EXISTS "Players" CASCADE;
DROP TABLE IF EXISTS "Teams" CASCADE;
DROP TABLE IF EXISTS "Deadlines" CASCADE;
DROP TABLE IF EXISTS "Tournaments" CASCADE;
DROP TABLE IF EXISTS "GuildConfig" CASCADE;
DROP TABLE IF EXISTS "StaffStats" CASCADE;

-- 3. Create the new relational tables

-- Table 1: GuildConfig (Cleaned up, no legacy columns)
CREATE TABLE "GuildConfig" (
    "Guild_ID" TEXT PRIMARY KEY,
    "Admin_Role_ID" TEXT,
    "Organizer_Role_ID" TEXT,
    "Helper_Role_ID" TEXT,
    "Judge_Role_ID" TEXT,
    "Recorder_Role_ID" TEXT,
    "Staff_Role_ID" TEXT,
    "Players_Role_ID" TEXT,
    "Organization_Name" TEXT DEFAULT 'Tournament Organizer',
    "Tournament_System_Name" TEXT DEFAULT 'Tournament System',
    "Updated_At" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Table 2: Tournaments (Added Map_Pool, isolated settings)
CREATE TABLE "Tournaments" (
    "Tournament_ID" TEXT PRIMARY KEY,
    "Guild_ID" TEXT REFERENCES "GuildConfig"("Guild_ID") ON DELETE CASCADE,
    "Tournament_Name" TEXT NOT NULL,
    "State" TEXT DEFAULT 'pending', -- pending, active, completed
    "Key" TEXT, -- Challonge API key/identifier
    "Challonge_Bracket_Link" TEXT,
    "Google_Sheet_Link" TEXT,
    "Attendance_Channel_ID" TEXT,
    "Transcript_Channel_ID" TEXT,
    "Schedule_Channel_ID" TEXT,
    "Result_Channel_ID" TEXT,
    "Deadline_Channel_ID" TEXT,
    "Closed_Ticket_Category_ID" TEXT,
    "Auto_Room_Creation" BOOLEAN DEFAULT FALSE,
    "Map_Pool" TEXT DEFAULT 'New Storm (2024), Arid Frontier, Islands of Iceland, Unexplored Rocks, Arctic, Lost City, Polar Frontier, Hidden Dragon, Monstrous Maelstrom, Two Samurai, Stone Peaks, Viking Bay, Rising Fortress, Greenlands, Old Storm',
    "Updated_At" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Table 3: Deadlines (Tournament Isolated)
CREATE TABLE "Deadlines" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Tournament_ID" TEXT REFERENCES "Tournaments"("Tournament_ID") ON DELETE CASCADE,
    "Round" INTEGER NOT NULL,
    "Deadline_Time" TIMESTAMP WITH TIME ZONE NOT NULL,
    "Created_At" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    CONSTRAINT "Deadlines_Tourney_Round_key" UNIQUE ("Tournament_ID", "Round")
);

-- Table 4: Teams (Participants)
CREATE TABLE "Teams" (
    "Team_ID" TEXT PRIMARY KEY,
    "Tournament_ID" TEXT REFERENCES "Tournaments"("Tournament_ID") ON DELETE CASCADE,
    "Team_Name" TEXT NOT NULL,
    "Captain_ID" TEXT,
    "Captain_IGN" TEXT,
    "Updated_At" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    UNIQUE ("Tournament_ID", "Team_Name")
);

-- Table 5: Players (Roster member list)
CREATE TABLE "Players" (
    "Player_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Team_ID" TEXT REFERENCES "Teams"("Team_ID") ON DELETE CASCADE,
    "Discord_ID" TEXT NOT NULL,
    "IGN" TEXT NOT NULL,
    "Game_ID" TEXT,
    "Title" TEXT,
    "Updated_At" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Table 6: Matches (Scheduled events and completed results merged)
CREATE TABLE "Matches" (
    "Match_ID" TEXT PRIMARY KEY,
    "Match_Name" TEXT,
    "Tournament_ID" TEXT REFERENCES "Tournaments"("Tournament_ID") ON DELETE CASCADE,
    "Round" INTEGER NOT NULL,
    "Group" TEXT,
    "Team1_ID" TEXT REFERENCES "Teams"("Team_ID") ON DELETE SET NULL,
    "Team2_ID" TEXT REFERENCES "Teams"("Team_ID") ON DELETE SET NULL,
    "Team1_Score" INTEGER DEFAULT 0,
    "Team2_Score" INTEGER DEFAULT 0,
    "Status" TEXT DEFAULT 'scheduled', -- scheduled, ongoing, completed, forfeited, disputed
    "Scheduled_Time" TIMESTAMP WITH TIME ZONE,
    "Channel_ID" TEXT,
    "Poster_Path" TEXT,
    "General_VOD" TEXT,
    "Recorder_VOD" TEXT,
    "Judge_VOD" TEXT,
    "recording_link" TEXT,
    "recorder_link" TEXT,
    "judge_link" TEXT,
    "results_message_id" TEXT,
    "results_channel_id" TEXT,
    "match_results_message_id" TEXT,
    "match_results_channel_id" TEXT,
    "Winner_ID" TEXT REFERENCES "Teams"("Team_ID") ON DELETE SET NULL,
    "Remarks" TEXT,
    "Screenshots_Count" INTEGER DEFAULT 0,
    "Disqualified" BOOLEAN DEFAULT FALSE,
    "Created_At" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    "Updated_At" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Table 7: MatchStaff (Multiple Staff with check-in confirmation logs)
CREATE TABLE "MatchStaff" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Match_ID" TEXT REFERENCES "Matches"("Match_ID") ON DELETE CASCADE,
    "User_ID" TEXT NOT NULL,
    "Name" TEXT NOT NULL,
    "Role" TEXT NOT NULL, -- 'Judge' or 'Recorder'
    "Confirmed" BOOLEAN DEFAULT FALSE,
    "Confirmed_At" TIMESTAMP WITH TIME ZONE,
    "Claimed_At" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    UNIQUE ("Match_ID", "User_ID", "Role")
);

-- Table 8: StaffStats (Leaderboard tracking)
CREATE TABLE "StaffStats" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Guild_ID" TEXT REFERENCES "GuildConfig"("Guild_ID") ON DELETE CASCADE,
    "User_ID" TEXT NOT NULL,
    "Name" TEXT NOT NULL,
    "Judge_Count" INTEGER DEFAULT 0,
    "Recorder_Count" INTEGER DEFAULT 0,
    "Total_Count" INTEGER DEFAULT 0,
    "Timestamp" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. Safe data copy using conditional PL/pgSQL
DO $$
BEGIN
    -- GuildConfig Copy
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'GuildConfig_old') THEN
        INSERT INTO "GuildConfig" (
            "Guild_ID", "Admin_Role_ID", "Organizer_Role_ID", "Helper_Role_ID", "Judge_Role_ID", "Recorder_Role_ID", "Staff_Role_ID", "Players_Role_ID", "Organization_Name", "Tournament_System_Name"
        )
        SELECT 
            "Guild_ID", "Admin_Role_ID", "Organizer_Role_ID", "Helper_Role_ID", "Judge_Role_ID", "Recorder_Role_ID", "Staff_Role_ID", "Players_Role_ID", 'Tournament Organizer', 'Tournament System'
        FROM "GuildConfig_old" ON CONFLICT DO NOTHING;
    END IF;

    -- Tournaments Copy
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'Tournaments_old') THEN
        INSERT INTO "Tournaments" (
            "Tournament_ID", "Guild_ID", "Tournament_Name", "State", "Key", "Challonge_Bracket_Link", "Attendance_Channel_ID", "Transcript_Channel_ID", "Schedule_Channel_ID", "Result_Channel_ID", "Deadline_Channel_ID", "Closed_Ticket_Category_ID"
        )
        SELECT 
            "Tournament_ID", "Guild_ID", "Tournament_Name", "State", "Key", "challonge_bracket_link", "Attendance_Channel_ID", "Transcript_Channel_ID", "Schedule_Channel_ID", "Result_Channel_ID", "Deadline_Channel_ID", "Closed_Ticket_Category_ID"
        FROM "Tournaments_old" ON CONFLICT DO NOTHING;
    END IF;

    -- StaffStats Copy
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'StaffStats_old') THEN
        INSERT INTO "StaffStats" ("Guild_ID", "User_ID", "Name", "Judge_Count", "Recorder_Count", "Total_Count")
        SELECT 
            "Guild_ID", "User_ID", "Name", "Judge_Count", "Recorder_Count", "Total_Count"
        FROM "StaffStats_old"
        ON CONFLICT DO NOTHING;
    END IF;
END $$;

-- 5. Clean up temporary _old tables
DROP TABLE IF EXISTS "GuildConfig_old" CASCADE;
DROP TABLE IF EXISTS "Tournaments_old" CASCADE;
DROP TABLE IF EXISTS "Events_old" CASCADE;
DROP TABLE IF EXISTS "Results_old" CASCADE;
DROP TABLE IF EXISTS "Deadlines_old" CASCADE;
DROP TABLE IF EXISTS "JudgeAssignments_old" CASCADE;
DROP TABLE IF EXISTS "StaffStats_old" CASCADE;

COMMIT;
