-- =========================================================================
-- SUPABASE / POSTGRESQL SCHEMA MIGRATION SCRIPT
-- Bot: Tournament Bot
-- Purpose: Create/Rearrange tables to match exact column header orders.
-- =========================================================================

-- WARNING: The scripts below are provided in two versions:
-- 1. MIGRATION & PRESERVE DATA (Recommended if you have active data)
-- 2. FRESH INSTALL (Destructive - drops and recreates empty tables)

-- Choose the block that suits your needs and run it in the Supabase SQL Editor.

-- =========================================================================
-- OPTION 1: MIGRATION & PRESERVE DATA (Recommended)
-- Renames old tables, creates new ones in correct column order,
-- copies existing data over, and then cleans up.
-- =========================================================================

-- Start Transaction
BEGIN;

-- 1. Rename existing tables if they exist
ALTER TABLE IF EXISTS "GuildConfig" RENAME TO "GuildConfig_old";
ALTER TABLE IF EXISTS "Tournaments" RENAME TO "Tournaments_old";
ALTER TABLE IF EXISTS "Events" RENAME TO "Events_old";
ALTER TABLE IF EXISTS "Results" RENAME TO "Results_old";
ALTER TABLE IF EXISTS "Challonge_Uploads" RENAME TO "Challonge_Uploads_old";
ALTER TABLE IF EXISTS "JudgeAssignments" RENAME TO "JudgeAssignments_old";
ALTER TABLE IF EXISTS "StaffStats" RENAME TO "StaffStats_old";

-- 2. Create new tables with exact column order

-- TABLE 1: GuildConfig
CREATE TABLE "GuildConfig" (
    "Guild_ID" text PRIMARY KEY,
    "Admin_Role_ID" text,
    "Organizer_Role_ID" text,
    "Helper_Role_ID" text,
    "Judge_Role_ID" text,
    "Recorder_Role_ID" text,
    "Staff_Role_ID" text,
    "Players_Role_ID" text,
    "organization_name" text,
    "tournament_system_name" text,
    "player_info_link" text,
    "player_info_format" text,
    "player_info_participant_channel_id" text,
    "Updated_At" text,
    -- Legacy columns included at the end to prevent legacy fallback errors
    "Challonge_Role_ID" text,
    "Challonge_Logs_Channel_ID" text,
    "Transcript_Logs_Channel_ID" text,
    "Closed_Category_ID" text,
    "Schedule_Channel_ID" text,
    "Results_Channel_ID" text,
    "channel_bracket" text,
    "Bot_Logs_Channel_ID" text,
    "Thumbnail_Channel_ID" text,
    "google_sheet_link" text,
    "sheetdb_api_url" text
);

-- TABLE 2: Tournaments
CREATE TABLE "Tournaments" (
    "Guild_ID" text,
    "Tournament_ID" text PRIMARY KEY,
    "Tournament_Name" text,
    "State" text,
    "Key" text,
    "challonge_bracket_link" text,
    "Attendance_Channel_ID" text,
    "Transcript_Channel_ID" text,
    "Schedule_Channel_ID" text,
    "Rules_Channel_ID" text,
    "Result_Channel_ID" text,
    "Deadline_Channel_ID" text,
    "Challonge_Logs_Channel_ID" text,
    "Transcript_Logs_Channel_ID" text,
    "Bot_Logs_Channel_ID" text,
    "Closed_Ticket_Category_ID" text,
    "Closed_Ticket_Category_2_ID" text,
    "Open_Category_1_ID" text,
    "Open_Category_2_ID" text,
    "Open_Category_3_ID" text,
    "Updated_At" text,
    "Captains_Sheet_Link" text,
    "Open_Category_4_ID" text,
    "Auto_Room_Creation" text,
    "Players_Role_ID" text
);

-- TABLE 3: Events
CREATE TABLE "Events" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Guild_ID" text,
    "Timestamp" text,
    "Event_ID" text,
    "Match_Name" text,
    "Tournament" text,
    "Round" text,
    "Group" text,
    "Date" text,
    "UTC_Time" text,
    "Team1_Captain_ID" text,
    "Team1_Captain_Name" text,
    "Team2_Captain_ID" text,
    "Team2_Captain_Name" text,
    "Judge_ID" text,
    "Judge_Name" text,
    "Recorder_ID" text,
    "Recorder_Name" text,
    "Channel_ID" text,
    "Status" text,
    "recording_link" text,
    "recorder_link" text,
    "judge_link" text,
    "results_message_id" text,
    "results_channel_id" text,
    "match_results_message_id" text,
    "match_results_channel_id" text,
    "Created_By_ID" text,
    "Created_By_Name" text
);

-- TABLE 4: Results
CREATE TABLE "Results" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Guild_ID" text,
    "Timestamp" text,
    "Event_ID" text,
    "Match_Name" text,
    "Tournament" text,
    "Round" text,
    "Group" text,
    "Winner_ID" text,
    "Winner_Name" text,
    "Winner_Score" text,
    "Loser_ID" text,
    "Loser_Name" text,
    "Loser_Score" text,
    "Judge_ID" text,
    "Judge_Name" text,
    "Recorder_ID" text,
    "Recorder_Name" text,
    "Remarks" text,
    "Screenshots_Count" text,
    "Disqualified" text,
    "recording_link" text,
    "recorder_link" text,
    "judge_link" text,
    "results_message_id" text,
    "results_channel_id" text
);

-- TABLE 5: Challonge_Uploads
CREATE TABLE "Challonge_Uploads" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Guild_ID" text,
    "Timestamp" text,
    "Match_ID" text,
    "Winner_Participant_ID" text,
    "Winner_Score" integer,
    "Loser_Score" integer,
    "Tournament_ID" text,
    "Uploaded_By_ID" text,
    "Uploaded_By_Name" text,
    "Status" text
);

-- TABLE 6: JudgeAssignments
CREATE TABLE "JudgeAssignments" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Guild_ID" text,
    "Timestamp" text,
    "Event_ID" text,
    "Judge_ID" text,
    "Judge_Name" text,
    "Tournament" text,
    "Round" text,
    "Date" text,
    "UTC_Time" text,
    "Action" text
);

-- TABLE 7: StaffStats
CREATE TABLE "StaffStats" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Guild_ID" text,
    "Timestamp" text,
    "User_ID" text,
    "Name" text,
    "Role_Updated" text,
    "Judge_Count" integer,
    "Recorder_Count" integer,
    "Total_Count" integer
);

-- TABLE 8: Deadlines
CREATE TABLE "Deadlines" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Guild_ID" text NOT NULL,
    "Round" text NOT NULL,
    "Deadline_Time" text NOT NULL,
    "Created_At" timestamp with time zone DEFAULT timezone('utc'::text, now()),
    CONSTRAINT "Deadlines_Guild_ID_Round_key" UNIQUE ("Guild_ID", "Round")
);

-- 3. Copy existing data (if old tables exist)

-- GuildConfig Data Copy
INSERT INTO "GuildConfig" (
    "Guild_ID", "Admin_Role_ID", "Organizer_Role_ID", "Helper_Role_ID", "Judge_Role_ID", "Recorder_Role_ID", "Staff_Role_ID", "Players_Role_ID", 
    "organization_name", "tournament_system_name", "player_info_link", "player_info_format", "player_info_participant_channel_id", "Updated_At",
    "Challonge_Role_ID", "Challonge_Logs_Channel_ID", "Transcript_Logs_Channel_ID", "Closed_Category_ID", "Schedule_Channel_ID", "Results_Channel_ID", 
    "channel_bracket", "Bot_Logs_Channel_ID", "Thumbnail_Channel_ID", "google_sheet_link", "sheetdb_api_url"
)
SELECT 
    "Guild_ID", "Admin_Role_ID", NULLIF("Admin_Role_ID", "Admin_Role_ID"), "Staff_Role_ID", "Judge_Role_ID", "Recorder_Role_ID", "Staff_Role_ID", "Challonge_Role_ID", 
    "organization_name", "tournament_system_name", "player_info_link", "player_info_format", "player_info_participant_channel_id", "Updated_At",
    "Challonge_Role_ID", "Challonge_Logs_Channel_ID", "Transcript_Logs_Channel_ID", "Closed_Category_ID", "Schedule_Channel_ID", "Results_Channel_ID", 
    "channel_bracket", "Bot_Logs_Channel_ID", "Thumbnail_Channel_ID", "google_sheet_link", "sheetdb_api_url"
FROM "GuildConfig_old" ON CONFLICT DO NOTHING;

-- Tournaments Data Copy
INSERT INTO "Tournaments" (
    "Guild_ID", "Tournament_ID", "Tournament_Name", "State", "Key", "challonge_bracket_link", 
    "Thumbnail_Channel_ID", "Attendance_Channel_ID", "Transcript_Channel_ID", "Schedule_Channel_ID", "Rules_Channel_ID", "Result_Channel_ID", "Deadline_Channel_ID",
    "Participant_Channel_ID", 
    "Challonge_Logs_Channel_ID", "Transcript_Logs_Channel_ID", "Bot_Logs_Channel_ID", 
    "Closed_Ticket_Category_ID", "Closed_Ticket_Category_2_ID", 
    "Open_Category_1_ID", "Open_Category_2_ID", "Open_Category_3_ID", 
    "Updated_At", "Captains_Sheet_Link", "Sheet_Link", "Open_Category_4_ID", "Auto_Room_Creation", "Admin_Role_ID", "Helper_Role_ID", "Thumbnail_URL"
)
SELECT 
    "Guild_ID", "Tournament_ID", "Tournament_Name", "State", "Key", "challonge_bracket_link", 
    COALESCE("Thumbnail_Channel_ID", ''), "Attendance_Channel_ID", "Transcript_Channel_ID", COALESCE("Schedule_Channel_ID", ''), "Rules_Channel_ID", "Result_Channel_ID", "Deadline_Channel_ID",
    COALESCE("Participant_Channel_ID", ''), 
    COALESCE("Challonge_Logs_Channel_ID", ''), COALESCE("Transcript_Logs_Channel_ID", ''), COALESCE("Bot_Logs_Channel_ID", ''), 
    "Closed_Ticket_Category_ID", "Closed_Ticket_Category_2_ID", 
    "Open_Category_1_ID", "Open_Category_2_ID", "Open_Category_3_ID", 
    "Updated_At", COALESCE("Captains_Sheet_Link", "Sheet_Link"), "Sheet_Link", "Open_Category_4_ID", "Auto_Room_Creation", "Admin_Role_ID", "Helper_Role_ID", "Thumbnail_URL"
FROM "Tournaments_old" ON CONFLICT DO NOTHING;

-- Events Data Copy
INSERT INTO "Events" (
    "id", "Guild_ID", "Timestamp", "Event_ID", "Tournament", "Round", "Group", "Date", "UTC_Time", 
    "Team1_Captain_ID", "Team1_Captain_Name", "Team2_Captain_ID", "Team2_Captain_Name", 
    "Judge_ID", "Judge_Name", "Channel_ID", "Status", "Created_By_ID", "Created_By_Name"
)
SELECT 
    "id", "Guild_ID", "Timestamp", "Event_ID", "Tournament", "Round", "Group", "Date", "UTC_Time", 
    "Team1_Captain_ID", "Team1_Captain_Name", "Team2_Captain_ID", "Team2_Captain_Name", 
    "Judge_ID", "Judge_Name", "Channel_ID", "Status", "Created_By_ID", "Created_By_Name"
FROM "Events_old" ON CONFLICT DO NOTHING;

-- Results Data Copy
INSERT INTO "Results" (
    "id", "Guild_ID", "Timestamp", "Tournament", "Round", "Group", "Winner_ID", "Winner_Name", "Winner_Score", 
    "Loser_ID", "Loser_Name", "Loser_Score", "Judge_ID", "Judge_Name", "Recorder_ID", "Recorder_Name", 
    "Remarks", "Screenshots_Count", "Disqualified"
)
SELECT 
    "id", "Guild_ID", "Timestamp", "Tournament", "Round", "Group", "Winner_ID", "Winner_Name", "Winner_Score", 
    "Loser_ID", "Loser_Name", "Loser_Score", "Judge_ID", "Judge_Name", "Recorder_ID", "Recorder_Name", 
    "Remarks", "Screenshots_Count", "Disqualified"
FROM "Results_old" ON CONFLICT DO NOTHING;

-- Challonge_Uploads Data Copy
INSERT INTO "Challonge_Uploads" (
    "id", "Guild_ID", "Timestamp", "Match_ID", "Winner_Participant_ID", "Winner_Score", "Loser_Score", 
    "Tournament_ID", "Uploaded_By_ID", "Uploaded_By_Name", "Status"
)
SELECT 
    "id", "Guild_ID", "Timestamp", "Match_ID", "Winner_Participant_ID", "Winner_Score", "Loser_Score", 
    "Tournament_ID", "Uploaded_By_ID", "Uploaded_By_Name", "Status"
FROM "Challonge_Uploads_old" ON CONFLICT DO NOTHING;

-- JudgeAssignments Data Copy
INSERT INTO "JudgeAssignments" (
    "id", "Guild_ID", "Timestamp", "Event_ID", "Judge_ID", "Judge_Name", "Tournament", "Round", "Date", "UTC_Time", "Action"
)
SELECT 
    "id", "Guild_ID", "Timestamp", "Event_ID", "Judge_ID", "Judge_Name", "Tournament", "Round", "Date", "UTC_Time", "Action"
FROM "JudgeAssignments_old" ON CONFLICT DO NOTHING;

-- StaffStats Data Copy
INSERT INTO "StaffStats" (
    "id", "Guild_ID", "Timestamp", "User_ID", "Name", "Role_Updated", "Judge_Count", "Recorder_Count", "Total_Count"
)
SELECT 
    "id", "Guild_ID", "Timestamp", "User_ID", "Name", "Role_Updated", "Judge_Count", "Recorder_Count", "Total_Count"
FROM "StaffStats_old" ON CONFLICT DO NOTHING;

-- 4. Clean up old tables
DROP TABLE IF EXISTS "GuildConfig_old";
DROP TABLE IF EXISTS "Tournaments_old";
DROP TABLE IF EXISTS "Events_old";
DROP TABLE IF EXISTS "Results_old";
DROP TABLE IF EXISTS "Challonge_Uploads_old";
DROP TABLE IF EXISTS "JudgeAssignments_old";
DROP TABLE IF EXISTS "StaffStats_old";

-- Commit Transaction
COMMIT;



-- =========================================================================
-- OPTION 2: FRESH INSTALL / RECREATE FROM SCRATCH (Destructive)
-- Drops existing tables and creates empty tables in the correct order.
-- Use this if you do NOT need to preserve any existing data.
-- =========================================================================

/*
BEGIN;

DROP TABLE IF EXISTS "GuildConfig" CASCADE;
DROP TABLE IF EXISTS "Tournaments" CASCADE;
DROP TABLE IF EXISTS "Events" CASCADE;
DROP TABLE IF EXISTS "Results" CASCADE;
DROP TABLE IF EXISTS "Challonge_Uploads" CASCADE;
DROP TABLE IF EXISTS "JudgeAssignments" CASCADE;
DROP TABLE IF EXISTS "StaffStats" CASCADE;

-- GuildConfig
CREATE TABLE "GuildConfig" (
    "Guild_ID" text PRIMARY KEY,
    "Admin_Role_ID" text,
    "Organizer_Role_ID" text,
    "Helper_Role_ID" text,
    "Judge_Role_ID" text,
    "Recorder_Role_ID" text,
    "Staff_Role_ID" text,
    "Players_Role_ID" text,
    "organization_name" text,
    "tournament_system_name" text,
    "player_info_link" text,
    "player_info_format" text,
    "player_info_participant_channel_id" text,
    "Updated_At" text,
    -- Fallback & compatibility columns
    "Challonge_Role_ID" text,
    "Challonge_Logs_Channel_ID" text,
    "Transcript_Logs_Channel_ID" text,
    "Closed_Category_ID" text,
    "Schedule_Channel_ID" text,
    "Results_Channel_ID" text,
    "channel_bracket" text,
    "Bot_Logs_Channel_ID" text,
    "Thumbnail_Channel_ID" text,
    "google_sheet_link" text,
    "sheetdb_api_url" text
);

-- Tournaments
CREATE TABLE "Tournaments" (
    "Guild_ID" text,
    "Tournament_ID" text PRIMARY KEY,
    "Tournament_Name" text,
    "State" text,
    "Key" text,
    "challonge_bracket_link" text,
    "Attendance_Channel_ID" text,
    "Transcript_Channel_ID" text,
    "Schedule_Channel_ID" text,
    "Rules_Channel_ID" text,
    "Result_Channel_ID" text,
    "Deadline_Channel_ID" text,
    "Challonge_Logs_Channel_ID" text,
    "Transcript_Logs_Channel_ID" text,
    "Bot_Logs_Channel_ID" text,
    "Closed_Ticket_Category_ID" text,
    "Closed_Ticket_Category_2_ID" text,
    "Open_Category_1_ID" text,
    "Open_Category_2_ID" text,
    "Open_Category_3_ID" text,
    "Updated_At" text,
    "Captains_Sheet_Link" text,
    "Open_Category_4_ID" text,
    "Auto_Room_Creation" text,
    "Players_Role_ID" text
);

-- Events
CREATE TABLE "Events" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Guild_ID" text,
    "Timestamp" text,
    "Event_ID" text,
    "Tournament" text,
    "Round" text,
    "Group" text,
    "Date" text,
    "UTC_Time" text,
    "Team1_Captain_ID" text,
    "Team1_Captain_Name" text,
    "Team2_Captain_ID" text,
    "Team2_Captain_Name" text,
    "Judge_ID" text,
    "Judge_Name" text,
    "Channel_ID" text,
    "Status" text,
    "Created_By_ID" text,
    "Created_By_Name" text
);

-- Results
CREATE TABLE "Results" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Guild_ID" text,
    "Timestamp" text,
    "Tournament" text,
    "Round" text,
    "Group" text,
    "Winner_ID" text,
    "Winner_Name" text,
    "Winner_Score" text,
    "Loser_ID" text,
    "Loser_Name" text,
    "Loser_Score" text,
    "Judge_ID" text,
    "Judge_Name" text,
    "Recorder_ID" text,
    "Recorder_Name" text,
    "Remarks" text,
    "Screenshots_Count" text,
    "Disqualified" text
);

-- Challonge_Uploads
CREATE TABLE "Challonge_Uploads" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Guild_ID" text,
    "Timestamp" text,
    "Match_ID" text,
    "Winner_Participant_ID" text,
    "Winner_Score" integer,
    "Loser_Score" integer,
    "Tournament_ID" text,
    "Uploaded_By_ID" text,
    "Uploaded_By_Name" text,
    "Status" text
);

-- JudgeAssignments
CREATE TABLE "JudgeAssignments" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Guild_ID" text,
    "Timestamp" text,
    "Event_ID" text,
    "Judge_ID" text,
    "Judge_Name" text,
    "Tournament" text,
    "Round" text,
    "Date" text,
    "UTC_Time" text,
    "Action" text
);

-- StaffStats
CREATE TABLE "StaffStats" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Guild_ID" text,
    "Timestamp" text,
    "User_ID" text,
    "Name" text,
    "Role_Updated" text,
    "Judge_Count" integer,
    "Recorder_Count" integer,
    "Total_Count" integer
);

-- Deadlines
CREATE TABLE "Deadlines" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Guild_ID" text NOT NULL,
    "Round" text NOT NULL,
    "Deadline_Time" text NOT NULL,
    "Created_At" timestamp with time zone DEFAULT timezone('utc'::text, now()),
    CONSTRAINT "Deadlines_Guild_ID_Round_key2" UNIQUE ("Guild_ID", "Round")
);

COMMIT;
*/
