-- =========================================================================
-- SUPABASE SCHEMA EXTENSION: WEB PORTAL, AUTH & MONETIZATION
-- Tables: WebUsers, TournamentSponsors, AffiliateProducts, SponsorClickLogs
-- =========================================================================

BEGIN;

-- 1. Web Master Admin Users (For Password-Based Super Admin & Developer Access)
CREATE TABLE IF NOT EXISTS "WebUsers" (
    "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "username" TEXT UNIQUE NOT NULL,
    "password_hash" TEXT NOT NULL,
    "role" TEXT DEFAULT 'super_admin', -- 'super_admin' or 'admin'
    "discord_id" TEXT, -- Optional linked Discord ID
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    "last_login" TIMESTAMP WITH TIME ZONE
);

-- 2. Tournament Sponsorship Banners
CREATE TABLE IF NOT EXISTS "TournamentSponsors" (
    "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "guild_id" TEXT NOT NULL,
    "tournament_id" TEXT, -- NULL means server-wide sponsor
    "sponsor_name" TEXT NOT NULL,
    "banner_image_url" TEXT NOT NULL,
    "target_url" TEXT NOT NULL,
    "slot_position" TEXT DEFAULT 'top_banner', -- 'top_banner', 'sidebar', 'bracket_footer', 'stage_sponsor'
    "impressions_count" BIGINT DEFAULT 0,
    "clicks_count" BIGINT DEFAULT 0,
    "is_active" BOOLEAN DEFAULT true,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Affiliate Gaming Store Products & Widgets
CREATE TABLE IF NOT EXISTS "AffiliateProducts" (
    "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "game_category" TEXT NOT NULL, -- e.g. 'Valorant', 'BGMI', 'Free Fire', 'General'
    "product_name" TEXT NOT NULL,
    "product_category" TEXT NOT NULL, -- 'mouse', 'headset', 'currency', 'controller', 'keyboard'
    "image_url" TEXT NOT NULL,
    "affiliate_url" TEXT NOT NULL,
    "badge_text" TEXT, -- e.g. 'Top Pick', '10% Off Diamonds', 'Pro Setup'
    "price_display" TEXT,
    "display_order" INT DEFAULT 0,
    "is_active" BOOLEAN DEFAULT true,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. Sponsor Click Analytics Log
CREATE TABLE IF NOT EXISTS "SponsorClickLogs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "sponsor_id" UUID REFERENCES "TournamentSponsors"("id") ON DELETE CASCADE,
    "guild_id" TEXT,
    "tournament_id" TEXT,
    "user_ip_hash" TEXT,
    "user_agent" TEXT,
    "timestamp" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Create Indexes for fast querying
CREATE INDEX IF NOT EXISTS idx_sponsors_guild ON "TournamentSponsors"("guild_id");
CREATE INDEX IF NOT EXISTS idx_sponsors_active ON "TournamentSponsors"("is_active");
CREATE INDEX IF NOT EXISTS idx_affiliates_game ON "AffiliateProducts"("game_category");
CREATE INDEX IF NOT EXISTS idx_affiliates_active ON "AffiliateProducts"("is_active");

COMMIT;
